# Generated by Django 4.1.2 on 2022-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=20, verbose_name='Tên đầu bếp')),
                ('position', models.IntegerField(choices=[(0, 'Bếp trưởng'), (1, 'Bản phó')], default=0, verbose_name='Vị trí')),
                ('yearOfBirth', models.DateField(null=True, verbose_name='Năm sinh')),
                ('homeTown', models.CharField(max_length=1000, verbose_name='Quê quán')),
                ('joiningDate', models.DateField(null=True, verbose_name='Ngày tham gia')),
                ('faceBook', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Twiiter')),
                ('instagram', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Instagram')),
                ('skype', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Skype')),
            ],
        ),
    ]
