# Generated by Django 4.1.2 on 2022-10-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0002_chefs_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs',
            name='position',
            field=models.CharField(choices=[('Bếp trưởng', 'Bếp trưởng'), ('Bếp phó', 'Bếp phó')], max_length=50, verbose_name='Vị trí'),
        ),
    ]
