# Generated by Django 4.1.2 on 2022-10-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0003_alter_chefs_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'Đầu bếp'},
        ),
    ]
