# Generated by Django 4.1.2 on 2022-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_alter_chefs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'Đầu bếp', 'verbose_name_plural': 'Đầu bếp'},
        ),
        migrations.AlterField(
            model_name='chefs',
            name='fullName',
            field=models.CharField(max_length=50, verbose_name='Tên đầu bếp'),
        ),
    ]
