# Generated by Django 4.1.2 on 2022-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Địa chỉ')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='Số điện thoại')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('location', models.TextField(max_length=100, null=True, verbose_name='Vị trí trên bản đồ')),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
