# Generated by Django 4.1.2 on 2022-10-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='location',
        ),
    ]
