# Generated by Django 4.1.2 on 2022-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='coordinates',
            field=models.TextField(null=True, verbose_name='Vị trí trên bản đồ'),
        ),
    ]
