# Generated by Django 4.1.2 on 2022-12-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactinfo_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Thông tin liên hệ', 'verbose_name_plural': 'Thông tin liên hệ'},
        ),
    ]
