# Generated by Django 4.1.3 on 2022-12-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='getInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='Số điện thoại')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('time', models.TimeField(verbose_name='Giờ')),
                ('amount', models.IntegerField(default=0, verbose_name='Số lượng')),
            ],
        ),
    ]
