# Generated by Django 4.1.2 on 2022-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_getintouch_reservations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='note',
            field=models.TextField(default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
