# Generated by Django 4.1.2 on 2022-10-06 10:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=1000, verbose_name='Artica Restaurant')),
                ('link', models.TextField(verbose_name='Link nhà hàng')),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Tiêu đề')),
                ('date', models.DateTimeField(verbose_name='Ngày đăng')),
                ('image', models.ImageField(upload_to='', verbose_name='Ảnh đại diện bài viết')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
    ]
