# Generated by Django 4.1.2 on 2022-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_status_alter_author_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Bản thảo'), (1, 'Bản hoàn chỉnh')], default=0, verbose_name='Trạng thái'),
        ),
    ]
