# Generated by Django 4.1.2 on 2022-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_date_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default=0, upload_to='', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='blog',
            name='note',
            field=models.TextField(default=0, verbose_name='Ghi chú'),
        ),
    ]
