# Generated by Django 4.1.2 on 2022-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_avatar_blog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='note',
            field=models.TextField(default='', verbose_name='Ghi chú'),
        ),
    ]
