# Generated by Django 4.1.2 on 2022-10-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ảnh đại diện'),
        ),
    ]
