# Generated by Django 4.1.2 on 2022-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
    ]
