# Generated by Django 4.1.2 on 2022-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='Ảnh instagram', max_length=100, verbose_name='Note')),
                ('image', models.ImageField(upload_to='', verbose_name='ảnh instagram feeds')),
            ],
        ),
    ]
