# Generated by Django 4.1.2 on 2022-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_instagramfeeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='Dingo Restaurant', max_length=100, verbose_name='Tên tác giả'),
        ),
    ]
