# Generated by Django 4.1.2 on 2022-12-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_author_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Tác giả', 'verbose_name_plural': 'Tác giả'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Bài viết', 'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='instagramfeeds',
            options={'verbose_name': 'Khoảnh khắc', 'verbose_name_plural': 'Khoảnh khắc'},
        ),
    ]
