# Generated by Django 4.1.2 on 2022-12-15 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='note',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày bình luận'),
        ),
    ]
