# Generated by Django 4.1.2 on 2022-12-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_delete_instagramfeeds_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Bình luận bài viết', 'verbose_name_plural': 'Bình luận bài viết'},
        ),
    ]
