# Generated by Django 4.1.2 on 2022-10-08 10:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Ghi chú')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung')),
            ],
        ),
    ]
