# Generated by Django 4.1.2 on 2022-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.TextField(null=True, verbose_name='Tiêu đề'),
        ),
    ]
