# Generated by Django 4.1.2 on 2022-10-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_alter_aboutus_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='Infor',
        ),
    ]
