# Generated by Django 4.1.2 on 2022-10-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_rename_aboutus_infor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infor',
            new_name='History',
        ),
    ]
