# Generated by Django 4.1.2 on 2022-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_rename_infor_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ảnh bài viết'),
        ),
    ]
