# Generated by Django 4.1.2 on 2022-10-09 08:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0005_history_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Tên khách hàng')),
                ('feedback', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung feedback')),
                ('created_at', models.DateTimeField(verbose_name='Ngày đăng')),
            ],
        ),
    ]
