# Generated by Django 4.1.2 on 2022-10-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0007_feedback_customer_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=100, verbose_name='Tên nhà hàng')),
                ('location', models.TextField(max_length=100, null=True, verbose_name='Vị trí trên bản đồ')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
                ('founding', models.DateField(null=True, verbose_name='Ngày thành lập')),
                ('faceBook', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Twiiter')),
                ('instagram', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Instagram')),
                ('skype', models.CharField(blank=True, default='#', max_length=1000, verbose_name='Skype')),
            ],
        ),
    ]
