# Generated by Django 4.1.2 on 2022-10-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0008_restaurantinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='location',
        ),
    ]
