# Generated by Django 4.1.2 on 2022-12-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0009_remove_restaurantinfo_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Phản hồi của khách hàng', 'verbose_name_plural': 'Phản hồi của khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Lịch sử nhà hàng', 'verbose_name_plural': 'Lịch sử nhà hàng'},
        ),
        migrations.AlterModelOptions(
            name='restaurantinfo',
            options={'verbose_name': 'Thông tin nhà hàng', 'verbose_name_plural': 'Thông tin nhà hàng'},
        ),
    ]
