# Generated by Django 4.1.2 on 2022-12-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.CharField(default='', max_length=100, verbose_name='Tuổi:'),
        ),
    ]
