# Generated by Django 4.1.2 on 2022-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_staff_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default='', upload_to='', verbose_name='Ảnh nhân viên'),
        ),
    ]
