# Generated by Django 4.1.3 on 2022-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_staff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.IntegerField(choices=[(0, 'Hoạt động'), (1, 'Không hoạt động')], default=0, verbose_name='Trạng thái'),
        ),
    ]
