# Generated by Django 4.1.3 on 2022-12-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_remove_food_category_delete_category_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('foodName', models.CharField(max_length=100, verbose_name='Tên món ăn')),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('foodName', models.CharField(max_length=100, verbose_name='Tên món ăn')),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('foodName', models.CharField(max_length=100, verbose_name='Tên món ăn')),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('foodName', models.CharField(max_length=100, verbose_name='Tên món ăn')),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
    ]
