# Generated by Django 4.1.3 on 2022-12-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_breakfast_status_dinner_status_lunch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái món ăn'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái món ăn'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái món ăn'),
        ),
        migrations.AlterField(
            model_name='special',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='special',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái món ăn'),
        ),
    ]
