# Generated by Django 4.1.3 on 2022-12-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_breakfast_status_alter_dinner_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Special',
            new_name='Food',
        ),
        migrations.DeleteModel(
            name='Breakfast',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
    ]
