# Generated by Django 4.1.2 on 2022-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_food_options_alter_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Số lượng'),
        ),
    ]
