# Generated by Django 4.1.2 on 2022-12-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_email_alter_orderproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adminnote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ghi chú quản trị viên'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Địa chỉ ip khách hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Mới'), (1, 'Đã thanh toán')], default=0, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, verbose_name='Tổng cộng'),
        ),
    ]
