# Generated by Django 4.1.2 on 2022-12-15 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_food_price'),
        ('order', '0003_alter_order_address_alter_order_adminnote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Món ăn đã được đặt', 'verbose_name_plural': 'Món ăn đã được đặt'},
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=20, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food', verbose_name='Món ăn'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Chấp Nhận', 'Chấp Nhận'), ('Đã hủy', 'Đã hủy')], default='New', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
