# Generated by Django 4.1.2 on 2022-12-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderproduct_options_orderproduct_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='amount',
        ),
    ]
